wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.6
    start_time: 1677359534.995117
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.6
      5: 0.13.10
      8:
      - 1
      - 2
      - 4
      - 5
d:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.4
image_size:
  desc: null
  value:
  - 512
  - 512
iterations:
  desc: null
  value: 400
lambda_:
  desc: null
  value: 0.4
lr:
  desc: null
  value: 0.005
n_filters:
  desc: null
  value: 32
noise:
  desc: null
  value: 0
prediction_stride:
  desc: null
  value: 4
seed:
  desc: null
  value: 0
subset_size:
  desc: null
  value: 0.7
