wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1677381618.420208
    t:
      1:
      - 1
      - 5
      - 53
      - 54
      - 55
      2:
      - 1
      - 5
      - 53
      - 54
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.10
      5: 0.13.10
      8:
      - 1
      - 5
d:
  desc: null
  value: 64
dropout:
  desc: null
  value: 0.1
image_size:
  desc: null
  value:
  - 512
  - 512
iterations:
  desc: null
  value: 500
lambda_:
  desc: null
  value: 0.4
lr:
  desc: null
  value: 0.001
n_filters:
  desc: null
  value: 128
noise:
  desc: null
  value: 0
prediction_stride:
  desc: null
  value: 4
seed:
  desc: null
  value: 0
subset_size:
  desc: null
  value: 0.5
