wandb_version: 1

d:
  value: 32
dropout:
  value: 0.1
image_size:
  value:
  - 512
  - 512
iterations:
  value: 400
lambda_:
  value: 0.4
lr:
  value: 0.005
n_filters:
  value: 32
noise:
  value: 0
prediction_stride:
  value: 4
seed:
  value: 0
subset_size:
  value: 0.5
