wandb_version: 1

d:
  value: 64
dropout:
  value: 0.5
image_size:
  value:
  - 512
  - 512
iterations:
  value: 300
lambda_:
  value: 0.5
lr:
  value: 0.005
n_filters:
  value: 128
noise:
  value: 0
prediction_stride:
  value: 4
seed:
  value: 0
subset_size:
  value: 0.7
